# Generated by Django 6.0.5 on 2026-05-17 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coffee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('espresso', 'Espresso'), ('latte', 'Latte'), ('cappuccino', 'Cappuccino'), ('cold_brew', 'Cold Brew'), ('pour_over', 'Pour Over'), ('other', 'Other')], default='other', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Coffee',
                'verbose_name_plural': 'Coffees',
                'ordering': ['name'],
            },
        ),
    ]
