# Generated by Django 6.0.5 on 2026-05-17 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coffee',
            name='image_url',
            field=models.URLField(blank=True, help_text='Paste a direct image URL for this coffee', max_length=500),
        ),
    ]
