# Generated by Django 6.0.5 on 2026-05-17 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_coffee_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='coffee',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload a photo of this coffee', null=True, upload_to='coffees/'),
        ),
        migrations.AlterField(
            model_name='coffee',
            name='image_url',
            field=models.URLField(blank=True, help_text='Or paste an image URL (used if no upload)', max_length=500),
        ),
    ]
